steps:
  # Fetch service infrastructure configurations
  #  - name: 'gcr.io/cloud-builders/git'
  #    args: [ 'clone', 'https://github.com/vm-mishchenko/p-dev-pipeline-api-infrastructure' ]

  - name: 'node'
    entrypoint: /bin/bash
    args:
      - -c # use "breakout syntax" to run bash commands directly
      - |
        ls -la

        node update-image-version.js ${_IMAGE_NAME}

        git config --global user.email "vm.mishchenko@gmail.com"
        git config --global user.name "vm.mishchenko"

        # commit changes back
        git add -A
        git commit -m 'API Service version was updated to: "${_IMAGE_NAME}"'

substitutions:
  _IMAGE_NAME: "EXPECTED_TO_GET_FROM_CALLER"
